context:
  name: font-ttf-twemoji
  version: 15.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/13rac1/twemoji-color-font/releases/download/v${{ version }}/TwitterColorEmoji-SVGinOT-${{ version }}.zip
  sha256: 9075de7a1c9dd660782d02b5c5be1c1524e16db13a6d7d4264b9aabbd056b692

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/fonts
    - install -v -m644 *.ttf $PREFIX/fonts/

requirements:
  build:
    - __unix

tests:
  - package_contents:
      files:
        - fonts/TwitterColorEmoji-SVGinOT.ttf

about:
  homepage: https://github.com/jdecked/twemoji
  repository: https://github.com/13rac1/twemoji-color-font
  summary: Twitter Unicode emoji color OpenType-SVG font
  description: |
    A color and B&W emoji SVG-OpenType / SVGinOT font built from the Twitter Emoji for Everyone artwork with support for ZWJ, skin tone diversity and country flags.
  license: MIT AND CC-BY-4.0
  license_file:
    - LICENSE.md
    - LICENSE-MIT.txt
    - LICENSE-CC-BY.txt

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
